---
- name: Get v2ray-plugin_linux_amd64
  unarchive:
    src: https://github.com/shadowsocks/v2ray-plugin/releases/download/v1.3.1/v2ray-plugin-linux-amd64-v1.3.1.tar.gz
    dest: "~/"
    remote_src: yes

- name: Copying v2ray-plugin to shadowsocks-libev directory
  shell: "cp -rf ~/v2ray-plugin_linux_amd64 {{ shadowsocks_location }}/v2ray-plugin"
...
